pas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pasapp.urls'))
]

pasapp/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
     path('', views.index, name='index'),
     path('login/', views.login_view, name='login'),
     path('logout/', views.logout_view, name='logout'),
     path('register/', views.register, name='register'),
     path('project/create/', views.create_project, name='create_project'),
     path('project/<int:project_id>/',
          views.project_details, name='project_details'),
     path('project/<int:project_id>/apply/', views.apply, name='apply'),
     path('project/<int:project_id>/applications/',
          views.project_applications, name='project_applications'),
     path('project/<int:project_id>/edit/',
          views.edit_project, name='edit_project'),
     path('project/<int:project_id>/copy/',
          views.copy_project, name='copy_project'),
     path('project/update_status/', views.set_project_status, name='update_project_status'),
     path('project/delete/', views.delete_project, name='delete_project'),
     path('projects/filter/', views.index, name='filter_projects'),
     path('projects/mine/', views.my_projects, name='my_projects'),
     path('applications/', views.my_applications, name='my_applications'),
     path('applications/update_priorities/',
          views.update_priorities, name='update_priorities'),
     path('applications/update_student_status/',
          views.update_student_status, name='update_student_status'),
     path('applications/update_professor_status/',
          views.update_professor_status, name='update_professor_status'),
     path('applications/add_comment/', views.add_comment, name='add_comment'),
     path('user/<str:username>/', views.profile_page, name='profile_page'),
     path('api/get_student/<str:username>', views.get_student, name='get_student'),
     url(r'^favicon\.ico$', RedirectView.as_view(url='/static/pasapp/favicon.ico')),
]

pasapp/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.utils.timezone import now

class Project(models.Model):
    title = models.CharField(max_length=200)
    professor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=2048)
    group_size = models.CharField(max_length=128, blank=True, null=True)  # TODO: Not implemented
    status = models.CharField(max_length=128, default="Draft")
    hidden = models.BooleanField(default=True) # only in effect if status is custom
    capacity = models.IntegerField(default=None, blank=True, null=True)
    date_created = models.DateTimeField(
        default=now, name='date_created')
    last_updated = models.DateTimeField(
        auto_now=True, name='last_updated')
    # Tags - see ProjectTag below

    class Meta:
        get_latest_by = "date_created"
        ordering = ["title"]
        indexes = [
            models.Index(fields=['professor'], name='project_by_professor_index'),
            models.Index(fields=['title'], name='project_by_title_index')
        ]

    def __str__(self):
        return f'{self.title}, by {self.professor}. Status: {self.status}'


class Application(models.Model):

    class ProfessorStatus(models.TextChoices):
        NONE = 'NONE'
        OFFERED = 'OFFR'
        DECLINED = 'DECL'
        RETRACTED = 'RETR'

    class StudentStatus(models.TextChoices):
        APPLIED = 'APPL'
        PREEMPTED = 'PRE', 'Preemptively Accepted'
        ACCEPTED = 'ACC'
        DECLINED = 'DECL'
        RETRACTED = 'RETR'

    def student_status_label(self):
        return Application.StudentStatus(self.student_status).label

    def professor_status_label(self):
        return Application.ProfessorStatus(self.professor_status).label

    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    group_members = models.ManyToManyField(User, related_name="member_projects", limit_choices_to=Q(groups__name = 'student'))
    message = models.CharField(max_length=2048)
    date_created = models.DateTimeField(default=now, name='date_created')
    last_updated = models.DateTimeField(
        auto_now=True, name='last_updated')
    priority = models.IntegerField(default=None, blank=True, null=True)
    professor_status = models.CharField(max_length=4, choices=ProfessorStatus.choices, default=ProfessorStatus.NONE, null=False)  
    student_status = models.CharField(max_length=4, choices=StudentStatus.choices, default=StudentStatus.APPLIED, null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('project', 'student'), name="unique_applications_per_project")
        ]
        get_latest_by = "date_created"
        ordering = [models.F("priority").asc(nulls_last=True), "-last_updated"]
        indexes = [
            models.Index(fields=['project', 'student'], name="app_by_project_index"),
            models.Index(fields=['student'], name='app_by_student_index'),
        ]

    def __str__(self):
        return f'{self.student} (+{self.group_members.count()}) on {self.project.title}. Status: {self.student_status_label()}, {self.professor_status_label()}'


class Comment(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_created = models.DateTimeField(default=now, name='date_created')
    message = models.CharField(max_length=2048)

    class Meta:
        get_latest_by = "date_created"
        ordering = ["date_created"]
        indexes = [
            models.Index(fields=['application'], name="comment_by_application_index"),
        ]
    
    def __str__(self):
        return f'{self.sender} on {self.application.student}\'s application to {self.application.project.title}'

class TagCategory(models.Model):
    category = models.CharField(max_length=128, unique=True)
    academic = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "tag categories"
        ordering = ['category']
        indexes = [
            models.Index(fields=['category'], name="tag_category_index"),
        ]

    def __str__(self):
        return self.category


class Tag(models.Model):
    name = models.CharField(max_length=256, unique=True)
    category = models.ForeignKey(
        TagCategory, on_delete=models.SET_NULL, blank=True, null=True, default=None)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('name', 'category'), name="unique_tags_per_category")
        ]
        ordering = ["category", "name"]
        indexes = [
            models.Index(fields=['category'], name="tag_by_category_index"),
        ]

    def __str__(self):
        return self.name


class ProjectTag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('project', 'tag'), name="unique_tags_per_project")
        ]
        ordering = ["project", "tag"]
        indexes = [
            models.Index(fields=['project'], name="tag_by_project_index"),
        ]

    def __str__(self):
        return f'{self.project.title}: {self.tag.name}'


class UserTag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=('user', 'tag'), name="unique_tags_per_user")
        ]
        ordering = ['user', 'tag']
        indexes = [
            models.Index(fields=['user'], name='user_tag_index'),
        ]

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}: {self.tag.name}'

pasapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(label='email', max_length=128, required=True)
    isProfessor = forms.BooleanField(
        label='Are you a professor?', required=False)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name",
                  "password1", "password2", "isProfessor")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        user_group = 'professor' if self.cleaned_data['isProfessor'] else 'student'
        user.groups.add(Group.objects.get(name=user_group))

        return user


class NewProjectForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200, widget=forms.Textarea)
    description = forms.CharField(
        label="Description", max_length=2048, widget=forms.Textarea)
    capacity = forms.IntegerField(label="Expected capacity of students/groups that can work on this project:", required=False)
    status = forms.CharField(
        label="Status", max_length=128, initial="Open", widget=forms.HiddenInput)
    hidden = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'hidden'}), # hidden checkbox cannot use hiddeninput
        required=False, label="")
    tags = forms.CharField(widget=forms.HiddenInput, required=False)


class ApplicationForm(forms.Form):
    message = forms.CharField(label="Message", max_length=2048, widget=forms.Textarea)
    preempt = forms.BooleanField(label="Automatically accept an offer", required=False)
    additional_students = forms.CharField(widget=forms.HiddenInput, required=False)

class CommentForm(forms.Form):
    application = forms.CharField(widget=forms.HiddenInput)
    message = forms.CharField(label="", max_length=2048, widget=forms.Textarea)

pasapp/templates/pasapp/components/application_comment_section.html
{% load custom_filters %}
{% load html_components %}
{% if comments %}
    {% for comment in comments %}
        <hr>
        {{comment.sender|name_link}}
        <em class="comment-date"> on {{comment.date_created|date:"DATE_FORMAT"}}:</em>
        <br>
        {{comment.message}}
    {% endfor %}
    {% if commentBox %}
        <hr>
        {% comment_box id %}
    {% endif %}
{% elif commentBox %}
    <hr style="margin-bottom:0;">
    <label for="id_message">Comment:</label>
    {% comment_box id %}
{% endif %}

pasapp/templates/pasapp/components/application_list_professor_interactive.html
{% load custom_filters %}
{% load html_components %}
<form action="/applications/update_professor_status/#NEXT" method="post" id="status_edit_form">
  {% csrf_token %}
  <input type="hidden" name="application" id="status_id">
  <input type="hidden" name="status" id="status_action">
</form>
<ul>
  {% for application in applications %}
  {% application_professor application comments|for_application:application buttons=True comment_box=commentBox %}
  {% endfor %}
</ul>

pasapp/templates/pasapp/components/application_professor.html
{% load custom_filters %}
{% load html_components %}
<li class="dashed-box application {{application|student_status|minify|lower}} {{application|professor_status|minify|lower}}">
    <div class="application-meta-container">
        {% if application.priority and application.priority <= 5 %}
            <div>Priority:</div>
            <div class="priority-number">{{application.priority}}</div>
        {% endif %}
        {% if application.student_status == 'PRE' %}
            <div class="application-status preempt">{{application|student_status|minify}}</div>
        {% elif application.professor_status == 'OFFR' %}
            <div class="application-status offer">{{application|professor_status|minify}}</div>
        {% endif %}
    </div>
    <div>
        {{application.student|name_link}}
        on {{application.date_created|date:"DATE_FORMAT"}}
        {% if application.group_members.all|length > 0 %}
            <br>    
            with {{application.group_members.all|name_list:True}}
        {% endif %}
        <br>
        <hr>
        {% comment %}<em>Description: </em>{{application.project.description}}<br/>{% endcomment %}
        {{application.message}}
        <br>
        {% if application|is_closed %}
            {% if application.professor_status == 'DECL' %}
            <b>Application declined.</b>
            {% else %}
            <b>Application retracted.</b>
            {% endif %}
        {% elif buttons %}
            {% if application.professor_status == 'NONE' %}
            <button type='button' onclick='offerApplication({{application.id}})'>Extend Offer</button>
            <button type='button' onclick='declineApplication({{application.id}})'>Reject Application</button>
            {% elif application.professor_status == 'OFFR' %}
                {% if application.student_status == 'ACC' %}
                <b>Offer accepted.</b>
                {% else %}
                <b>Offer extended.</b>
                {% endif %}
            {% elif application.professor_status == 'DECL' %}
            <b>Application declined.</b>
            {% endif %}
        {% endif %}
        
        {% application_comment_section application.id comments comment_box=commentBox %}
    </div>
</li>

pasapp/templates/pasapp/components/application_student.html
{% load custom_filters %}
{% load html_components %}
<li class="dashed-box application {{application|student_status|minify|lower}} {{application|professor_status|minify|lower}}">
    <div class="application-meta-container">
        {% if application.priority and application.priority <= 5 %}
            <div>Priority:</div>
            <div class="priority-number">{{application.priority}}</div>
        {% endif %}
        {% if studentStatus == 'PRE' %}
            <div class="application-status preempt">{{application|student_status|minify}}</div>
        {% elif professorStatus == 'OFFR' %}
            <div class="application-status offer">{{application|professor_status|minify}}</div>
        {% endif %}
    </div>
    <div>
        <a href="/project/{{application.project.id}}" class="undecorated-link">
            <b>{{application.project.title}}</b>
        </a> 
        by 
        <a href="/user/{{application.project.professor.username}}" class="undecorated-link underline-hover">
            {{application.project.professor.first_name}} {{application.project.professor.last_name}}
        </a>
        <br>
        {% if application.student.username != user.username %}
            {{application.student.first_name}} {{application.student.last_name}}
            applied
        {%else%}
            You applied
        {% endif %}
        on {{application.date_created|date:"DATE_FORMAT"}}
        {% if application.group_members.all|length > 0 %}
            <br>    
            with {{application.group_members.all|name_list}}
        {% endif %}
        {% if application.student.username != user.username %}
            <button type="button" onclick="leaveGroup({{application.id}})">Leave group</button>
        {% endif %}
        <br>
        {% if professorStatus != 'NONE' %}
            {{application.project.professor.first_name}} {{application.project.professor.last_name}} 
            {% if professorStatus == 'OFFR' %}
            offered you this project.
            {% elif professorStatus == 'DECL' %}
            declined this application.
            {% elif professorStatus == 'RETR' %}
            retracted this offer.
            {% endif %}
            <br>
        {% endif %}
        {% if professorStatus == 'OFFR'%}
            {% if studentStatus == 'ACC' %}
            You accepted this project.<br>
            {% elif studentStatus == 'DECL' %}
            You declined this project.<br>
            {% endif %}
        {% endif %}
        {% if studentStatus == 'RETR' %}
            You retracted this application.<br>
        {% endif %}
        {% if application.student.username == user.username %}
            {% if checkbox %}
                Automatically accept offer: 
                <input type="checkbox" class="low-checkbox"
                id="{{application.id}}" onclick="updateAppStatus(this)"
                {% if studentStatus == 'PRE' %} checked {% endif %}><br>
            {% elif responses %}
                <button type='button' onclick='acceptOffer({{application.id}})'>Accept Project Offer</button>
                <button type='button' onclick='declineOffer({{application.id}})'>Reject Offer</button>
            {% endif %}
            {% if professorStatus != 'OFFR' and not application|is_closed %}
                <button type='button' onclick='retractApplication({{application.id}})'>Retract Application</button><br>
            {% endif %}
        {% endif %}
        <hr>
        {% comment %}<em>Description: </em>{{application.project.description}}<br/>{% endcomment %}
        {{application.message}}
        <br>
        {% application_comment_section application.id comments comment_box=True %}
    </div>
</li>

pasapp/templates/pasapp/components/comment_box.html
<form
  action="/applications/add_comment/#NEXT"
  method="post"
  id="new-comment-form"
>
  {% csrf_token %} {{ form }}
  <input type="submit" value="Submit Comment" />
</form>

pasapp/templates/pasapp/components/status_select.html
<select id="status-dropdown" oninput="setStatus(this)" >
    <option value="" disabled selected>Select status</option>
    <option value="Open">Open</option>
    <option value="Draft">Draft</option>
    <option value="Closed">Closed</option>
</select>
<label for="custom-status-checkbox" id="custom-status-label">or enter custom:</label>
<input type="checkbox" id="custom-status-checkbox" onclick="toggleCustomStatus(this)">
<span class="dashed-box status-box">
    <input type="text" placeholder="Custom status" maxlength=128 id="custom-status-textfield" oninput="setCustomStatus(this)"><br/>
    <label for="custom-status-visibility-checkbox">hidden from view:</label>
    <input type="checkbox" id="custom-status-visibility-checkbox" onclick="toggleCustomStatusVisibility(this)" class="low-checkbox">
</span>

pasapp/templates/pasapp/components/tagbox_categorized.html
{% load html_components %}

{% if onclick %}
<ul id="{{id}}" class="tagBox closable categorized">
{% else %}
<ul id="{{id}}" class="tagBox categorized">
{% endif %}
    {% for category, tags in tagsByCategory.items %}
    <ul class="tagCategory {{category|slugify}}" meta="{{category}}">
        <h3>{{category}}</h3>
        {% for tag in tags %}
            {% tagbubble tag onclick %}
        {% endfor %}
    </ul>
    {% endfor %}
</ul>

pasapp/templates/pasapp/components/tagbox_static.html
{% load html_components %}

<ul id="tagBox">
    {% for pair in tagPairs %}
        {% tagbubble pair.tag %}
    {% endfor %}
</ul>

pasapp/templates/pasapp/components/tagbubble.html
{% if onclick %}
    <li class="tag tag-bubble {{ tag.category|lower|slugify }}" title="{{tag.category}}" onclick="removeTag(this, {{tag.id}})">{{tag.name}}</li>
{% else %}
    <li class="tag tag-bubble {{ tag.category|lower|slugify }}" title="{{tag.category}}">{{tag.name}}</li>
{% endif %}

pasapp/templates/pasapp/components/tagfilters.html
{% load html_components %}
{% load custom_filters %}
{% for category, tags in tagsByCategory.items %}
<div class="filter-category">
    <div class="filter-header" onclick="collapse(this)">
        <h5 class="nobreak click-pointer">{{category}}</h5>
        <div class="tag tag-bubble {{ category|lower|slugify }}"></div>
    </div>
    <div class="collapsible">
    {% for tag in tags %}
        <div class="checkbox-row">
            <input type="hidden" name="tag{{tag.id}}" id="tag{{tag.id}}" value="{{selectedTags|get:tag.id}}">
            {{ selectedTags|ternary_checkbox:tag.id }}
            <label for="tag{{tag.id}}" class="click-pointer {{ tag.category|lower|slugify }}" onclick="filterLabel(this)">{{tag.name}}</label>
            <br/>
        </div>
    {% endfor %}
    </div>
</div>
{% endfor %}

pasapp/templates/pasapp/components/tags_dropdown.html
<select id="tagDropdown" oninput="addTag(this)" >
    <option value="" disabled selected>Select tags</option>
    {% for category, tags in tagsByCategory.items %}
    <optgroup label={{category}}>
        {% for tag in tags %}
            <option value="{{tag.id}}" meta="{{tag.category}}">{{tag.name}}</option>
        {% endfor %}
    </optgroup>
    {% endfor %}
</select>