pas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pasapp.urls'))
]

pasapp/urls.py
from django.views.generic import RedirectView
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
     path('', views.index, name='index'),
     path('login/', views.login_view, name='login'),
     path('logout/', views.logout_view, name='logout'),
     path('register/', views.register, name='register'),
     path('project/create/', views.create_project, name='create_project'),
     path('project/<int:project_id>/',
          views.project_details, name='project_details'),
     path('project/<int:project_id>/apply/', views.apply, name='apply'),
     path('project/<int:project_id>/applications/',
          views.project_applications, name='project_applications'),
     path('project/<int:project_id>/edit/',
          views.edit_project, name='edit_project'),
     path('project/<int:project_id>/copy/',
          views.copy_project, name='copy_project'),
     path('project/update_status/', views.set_project_status, name='update_project_status'),
     path('project/delete/', views.delete_project, name='delete_project'),
     path('projects/filter/', views.index, name='filter_projects'),
     path('projects/mine/', views.my_projects, name='my_projects'),
     path('applications/', views.my_applications, name='my_applications'),
     path('applications/update_priorities/',
          views.update_priorities, name='update_priorities'),
     path('applications/update_student_status/',
          views.update_student_status, name='update_student_status'),
     path('applications/update_professor_status/',
          views.update_professor_status, name='update_professor_status'),
     path('applications/add_comment/', views.add_comment, name='add_comment'),
     path('user/<str:username>/', views.profile_page, name='profile_page'),
     path('api/get_student/<str:username>', views.get_student, name='get_student'),
     url(r'^favicon\.ico$', RedirectView.as_view(url='/static/pasapp/favicon.ico')),
]

pasapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group, User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(label='email', max_length=128, required=True)
    isProfessor = forms.BooleanField(
        label='Are you a professor?', required=False)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name",
                  "password1", "password2", "isProfessor")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        user_group = 'professor' if self.cleaned_data['isProfessor'] else 'student'
        user.groups.add(Group.objects.get(name=user_group))

        return user


class NewProjectForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200, widget=forms.Textarea)
    description = forms.CharField(
        label="Description", max_length=2048, widget=forms.Textarea)
    capacity = forms.IntegerField(label="Expected capacity of students/groups that can work on this project:", required=False)
    status = forms.CharField(
        label="Status", max_length=128, initial="Open", widget=forms.HiddenInput)
    hidden = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'hidden'}), # hidden checkbox cannot use hiddeninput
        required=False, label="")
    tags = forms.CharField(widget=forms.HiddenInput, required=False)


class ApplicationForm(forms.Form):
    message = forms.CharField(label="Message", max_length=2048, widget=forms.Textarea)
    preempt = forms.BooleanField(label="Automatically accept an offer", required=False)
    additional_students = forms.CharField(widget=forms.HiddenInput, required=False)

class CommentForm(forms.Form):
    application = forms.CharField(widget=forms.HiddenInput)
    message = forms.CharField(label="", max_length=2048, widget=forms.Textarea)

pasapp/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.http.response import HttpResponseBadRequest, HttpResponseForbidden, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, JsonResponse
from django.db.models import F, Q

from pasapp.forms import ApplicationForm, NewProjectForm, NewUserForm,CommentForm
from pasapp.models import Application, Comment, Project, ProjectTag, UserTag, Tag, TagCategory
from pasapp.utils import application_declined, contextWithHeader, get_next, student_accepted, project_closed
from pasapp.templatetags.custom_filters import is_professor, is_student, professor_status, student_status
from pasapp.queries import *


revoked_query = Q(student_status=Application.StudentStatus.RETRACTED) | Q(student_status=Application.StudentStatus.DECLINED)
declined_query = Q(professor_status=Application.ProfessorStatus.DECLINED)
app_closed_query = revoked_query | declined_query

def index(request):
    '''
    Lists all active projects. Also handles filtering those projects via POST requests.
    URL: /
    '''
    included_professor_ids = []
    category_filters = {} # category: [IDs to include, IDs to exclude]
    selected_tags = {} # id: 'I' or 'E'

    if request.method == "POST":
        post_request = request.POST
        # Sort the IDs sent by the filter post request into professor IDs and tag IDs
        for key in post_request.keys():
            if key.startswith("prof"):
                included_professor_ids.append(int(key.replace("prof", "", 1)))
            elif key.startswith("tag"):
                if post_request[key] == '': continue
                id = int(key.replace("tag", "", 1))
                tag = Tag.objects.get(pk=id)
                cat = tag.category
                if cat not in category_filters:
                    category_filters[cat] = ([], [])
                cat_incl, cat_excl = category_filters[cat]
                if post_request[key] == 'I':
                    cat_incl.append(id)
                    selected_tags[id] = 'I'
                elif post_request[key] == 'E':
                    cat_excl.append(id)
                    selected_tags[id] = 'E'
    else:
        user = request.user
        
        if (is_student(user)):
            exclusion_categories = [TagCategory.objects.get(category="Prerequisite Class")] # TODO: Generalize using a field in TagCategory model
            tags = [pair.tag for pair in UserTag.objects.filter(user=user)]
            student_prerequisites = []
            for tag in tags:
                cat = tag.category
                if cat not in category_filters:
                    category_filters[cat] = ([], [])
                cat_incl, cat_excl = category_filters[cat]
                if cat in exclusion_categories:
                    student_prerequisites.append(tag.id)
                else:
                    cat_incl.append(tag.id)
                    selected_tags[tag.id] = 'I'
            missing_prerequisites = Tag.objects.filter(category__in=exclusion_categories).exclude(id__in=student_prerequisites)
            for cat in exclusion_categories:
                category_filters[cat] = ([], [])
            for tag in missing_prerequisites:
                cat_incl, cat_excl = category_filters[tag.category]
                cat_excl.append(tag.id)
                selected_tags[tag.id] = 'E'
    
    projects = get_open_projects()
    project_tags = get_open_tags()

    if included_professor_ids:
        projects = projects.filter(professor_id__in=included_professor_ids)
        project_tags = project_tags.filter(project__in=projects)

    if category_filters:
        for cat in category_filters:
            cat_incl, cat_excl = category_filters[cat]
            if cat_incl:
                cat_project_tags = project_tags.filter(tag_id__in=cat_incl)
                cat_project_ids = [pair.project.id for pair in cat_project_tags]
                projects = projects.filter(id__in=cat_project_ids)
                project_tags = project_tags.filter(project_id__in=cat_project_ids)
            if cat_excl:
                cat_project_tags = project_tags.filter(tag_id__in=cat_excl)
                cat_project_ids = [pair.project.id for pair in cat_project_tags]
                projects = projects.exclude(id__in=cat_project_ids)
                project_tags = project_tags.exclude(project_id__in=cat_project_ids)
    
    application_info = {}
    for project in projects:
        open_apps = Application.objects.filter(project=project).exclude(app_closed_query)
        offered = open_apps.filter(professor_status='OFFR')
        application_info[project.id] = (offered.count(), open_apps.count())

    tag_filters = Tag.objects.all()
    # Only show professors who have published a project
    professor_filters = {
        project.professor for project in get_open_projects()}

    context = {'projects': projects, 'projectTags': project_tags, 'applicationInfo': application_info, 
                'allTags': tag_filters, 'professors': professor_filters,
               'selectedTags': selected_tags, 'selectedProfessors': included_professor_ids}
    return render(request, 'pasapp/pages/projects.html', contextWithHeader(context, request))


def project_details(request, project_id):
    '''
    Shows more details about the given project, including number of applicants
    URL: /project/<id>
    '''
    if is_professor(request.user):
        return professor_project_details(request, project_id)
    else:
        return student_project_details(request, project_id)

def student_project_details(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    apps = Application.objects.filter(project=project_id)
    num_applicants = apps.count()
    num_offered = apps.filter(professor_status='OFFR').exclude(app_closed_query).count()
    student_application = Application.objects.filter(project=project_id, student=request.user).first() if is_student(request.user) else None
    project_tags = ProjectTag.objects.filter(project=project)
    project_tags = [pair.tag for pair in project_tags]
    comments = Comment.objects.filter(application=student_application)
    context = {'project': project, 'numApplicants': num_applicants, 'numOffered': num_offered, 'projectTags': project_tags, 'student_application': student_application, 'comments': comments}
    return render(request, 'pasapp/pages/student_project_details.html', contextWithHeader(context, request))

def professor_project_details(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    applications = Application.objects.filter(project=project_id).order_by('-date_created')
    comments = Comment.objects.filter(application__in=applications)
    project_tags = ProjectTag.objects.filter(project=project)
    project_tags = [pair.tag for pair in project_tags]
    context = {'project': project, 'applications': applications, 'comments': comments, 'projectTags': project_tags}
    return render(request, 'pasapp/pages/professor_project_details.html', contextWithHeader(context, request))

@login_required
@user_passes_test(is_professor)
def my_projects(request):
    professor = request.user
    all_projects = Project.objects.filter(professor=professor)

    drafts = all_projects.filter(status='Draft')
    all_projects = all_projects.exclude(status='Draft')

    open_projects = get_open_projects(all_projects)
    other = all_projects.exclude(id__in=[project.id for project in open_projects])

    all_applications = Application.objects.filter(project__in=open_projects) # ignores applications for closed and draft projects
    project_applications = {project.id: 0 for project in open_projects}
    applied_project_ids = all_applications.values_list('project__id', flat=True)
    for id in applied_project_ids:
        project_applications[id] += 1

    applied = open_projects.filter(pk__in=set(applied_project_ids)) # TODO: sort by recent application
    open_projects = open_projects.exclude(pk__in=set(applied_project_ids))

    context = {'drafts': drafts, 'applied': applied, 'open': open_projects, 'other': other, 'projectApplications': project_applications}
    return render(request, 'pasapp/pages/my_projects.html', contextWithHeader(context, request))

@login_required
@user_passes_test(is_student)
def apply(request, project_id):
    '''
    Form page that allows a student to apply for a project
    URL: /project/<id>/apply
    '''
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            student = request.user
            message = form.cleaned_data.get('message')
            preempt = form.cleaned_data.get('preempt')
            student_status = Application.StudentStatus.PREEMPTED if preempt else Application.StudentStatus.APPLIED
            application = Application(
                project=project, student=student, message=message, student_status=student_status)
            application.save()

            User = get_user_model()
            group_users = form.cleaned_data.get('additional_students').split(' ')
            for student in group_users:
                if student == '':
                    continue
                student_object = User.objects.get(username=student)
                application.group_members.add(student_object)
            return redirect(f"/project/{project_id}/")
    form = ApplicationForm()
    context = {'project': project, 'form': form}
    return render(request, 'pasapp/pages/create_application.html', contextWithHeader(context, request))


@login_required
def project_applications(request, project_id): # semi-deprecated
    '''

pasapp/templates/pasapp/pages/copy_project.html
{% extends 'pasapp/templates/base_template.html' %} 

{% load static %}

{% block imports %}
    <script src="{% static 'pasapp/js/tag_edit.js' %}"></script>
    <script>
        {% for projectTag in projectTags %}
            tagSet.add({{projectTag.id}});
        {% endfor %}
    </script>
    <script src="{% static 'pasapp/js/project_status_edit.js' %}"></script>
    <script>
        initialStatus = "Open";
    </script>
    <script>
        function redirectSelf() {
            const form = document.getElementById('copy-project-form');
            form.action = '/project/create/?next=/project/{{project.id}}/copy/';
            form.submit();
        }
    </script>
{% endblock %}
{% block title %} Copying {{project.title}} {% endblock %} 
{% block onload %} setInitialStatus() {% endblock %}
{% block content %}
    <form action="/project/create/?next=/projects/mine/" method="post" id="copy-project-form">
        {% csrf_token %} {{ form.as_p }}
        
        {% load html_components %}
        <p>{% status_select %}</p>

        {% tags_dropdown tags %}
        <br>
        {% tagbox_categorized projectTags True %}
        <br>
        <input type="submit" value="Create Copy"/>
        <input type="button" value="Create and start another" onclick="redirectSelf()"/>
    </form>
{% endblock %}

pasapp/templates/pasapp/pages/create_application.html
{% extends 'pasapp/templates/base_template.html' %} 
{% load static %}

{% block title %} Applying for {{project.title}} {% endblock %} 
{% block imports %}
<script src="{% static 'pasapp/js/group_edit.js' %}"></script>
{% endblock %}
{% block content %} 
    <h1>Apply for {{project.title}}</h1>
    <p>Professor: {{project.professor.first_name}} {{project.professor.last_name}}</p>
    <form action="/project/{{project.id}}/apply/" method="post">
      {% csrf_token %} {{ form.as_p }}
      <p>Additional group members:
        <input type="text" id="user-entry" placeholder="Enter a username..." onkeydown="memberKeyDown(event)">
        <button type="button" onclick="addUser()">Add</button>
      </p>
      <div id="user-error-notifier" class="hidden"></div>
      <div id="user-box" class="user-box"></div>
      <input type="submit" value="Apply" />
    </form>
{% endblock %}

pasapp/templates/pasapp/pages/create_project.html
{% extends 'pasapp/templates/base_template.html' %} 

{% load static %}

{% block imports %}
    <script src="{% static 'pasapp/js/tag_edit.js' %}"></script>
    <script src="{% static 'pasapp/js/project_status_edit.js' %}"></script>
    <script>
        function redirectSelf() {
            const form = document.getElementById('new-project-form');
            form.action = '/project/create/?next=/project/create/';
            form.submit();
        }
    </script>
{% endblock %}
{% block title %} New Project {% endblock %} 
{% block content %}
    {% load html_components %}
    <form action="/project/create/?next={{next}}" method="post" id="new-project-form">
        {% csrf_token %} {{ form.as_p }}

        <p>{% status_select %}</p>
        
        {% tags_dropdown tags %}
        <br>
        {% tagbox_categorized onclick=True %}
        <br>
        <input type="submit" value="Create Project"/>
        <input type="button" value="Create and start another" onclick="redirectSelf()"/>
    </form>
{% endblock %}

pasapp/templates/pasapp/pages/edit_project.html
{% extends 'pasapp/templates/base_template.html' %} 

{% load static %}

{% block imports %}
    <script src="{% static 'pasapp/js/tag_edit.js' %}"></script>
    <script>
        {% for projectTag in projectTags %}
            tagSet.add({{projectTag.id}});
        {% endfor %}
    </script>
    <script src="{% static 'pasapp/js/project_status_edit.js' %}"></script>
    <script>
        initialStatus = "{{project.status}}";
    </script>
{% endblock %}
{% block title %} Editing {{project.title}} {% endblock %} 
{% block onload %} setInitialStatus() {% endblock %}
{% block content %}
    <form action="/project/{{project.id}}/edit/?next={{next}}" method="post">
        {% csrf_token %} {{ form.as_p }}
        
        {% load html_components %}
        <p>{% status_select %}</p>

        {% tags_dropdown tags %}
        <br>
        {% tagbox_categorized projectTags True %}
        <br>
        <input type="submit" value="Update Project"/>
    </form>
{% endblock %}

pasapp/templates/pasapp/pages/login.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} Login {% endblock %}
{% block content %}
<form action="/login/" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Log In" />
</form>
{% endblock %}

pasapp/templates/pasapp/pages/my_projects.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} My Projects {% endblock %}

{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/projects_actions.js' %}></script>
{% endblock %}

{% block onload %} {% endblock %}
{% block content %}
    <div class="floating-header" style="height: 3em;">
        <div>
            <a href="/project/create/?next=/projects/mine/" class="undecorated-link nav-item">➕ Add new project</a>
        </div>
    </div>
    <form action="/project/update_status/?next=/projects/mine/" method="post" id="update_status_form">
        {% csrf_token %}
        <input type="hidden" name="project" id="status_id">
        <input type="hidden" name="action" id="status_action">
    </form>
    <form action="/project/delete/?next=/projects/mine/" method="post" id="delete_project_form">
        {% csrf_token %}
        <input type="hidden" name="project" id="delete_id">
    </form>
    {% load custom_filters %}
    {% if drafts %}
        <h2>Drafts</h2>
        <ul class="project-list">
            {% for project in drafts %}
            <li class="dashed-box project-listing draft">
                <a href="{% url 'edit_project' project.id %}" class="undecorated-link underline-hover" title="Edit draft"><b>{{ project.title }}</b></a>
                <br/>
                {{project.description}}
                <br/>
                <a href="{% url 'edit_project' project.id %}?next=/projects/mine/"><button>✏️ Edit</button></a>
                <a href="{% url 'copy_project' project.id %}"><button>📄 Copy</button></a>
                <button onclick="publishProject({{project.id}})">📢 Publish</button>
                <button onclick="deleteProject({{project.id}})">❌ Delete</button>
            </li>
            {% endfor %}
        </ul>
        <hr>
    {% endif %}
    {% if applied %}
        <h2>Projects with applications</h2>
        <ul class="project-list">
            {% for project in applied %}
            <li class="dashed-box project-listing">
                <a href="{% url 'project_details' project.id %}" class="undecorated-link underline-hover" title="View project details"><b>{{ project.title }}</b></a>
                <br/>
                {{project.description}}
                <br/>
                <b>Status:</b> {{project.status}}
                <br/>
                🛈 <b>{{ projectApplications|get:project.id }} students have applied so far.</b>
                <br/>
                <a href="{% url 'project_details' project.id %}"><button>🔍 View</button></a>
                <a href="{% url 'edit_project' project.id %}?next=/projects/mine/"><button>✏️ Edit</button></a>
                <button onclick="closeProject({{project.id}})">🔒 Close</button>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if open %}
        <h2>Open projects</h2>
        <ul class="project-list">
            {% for project in open %}
            <li class="dashed-box project-listing">
                <a href="{% url 'project_details' project.id %}" class="undecorated-link underline-hover" title="View project details"><b>{{ project.title }}</b></a>
                <br/>
                {{project.description}}
                <br/>
                <b>Status:</b> {{project.status}}
                <br/>
                🛈 No applications.
                <br/>
                <a href="{% url 'edit_project' project.id %}?next=/projects/mine/"><button>✏️ Edit</button></a>
                <button onclick="closeProject({{project.id}})">🔒 Close</button>
                <button onclick="deleteProject({{project.id}})">❌ Delete</button>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if other %}
        <hr>
        <h2>Closed projects</h2>
        <ul class="project-list">
            {% for project in other %}
            <li class="dashed-box project-listing closed">
                <a href="{% url 'project_details' project.id %}" class="undecorated-link underline-hover" title="View project details"><b>{{ project.title }}</b></a>
                <br/>
                {{project.description}}
                <br/>
                <b>Status:</b> {{project.status}}
                <br/>
                <a href="{% url 'edit_project' project.id %}?next=/projects/mine/"><button>✏️ Edit</button></a>
                <a href="{% url 'copy_project' project.id %}"><button>📄 Copy</button></a>
                <button onclick="deleteProject({{project.id}})">❌ Delete</button>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

pasapp/templates/pasapp/pages/professor_applications.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} My Applications {% endblock %}
{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/app_prof_edit.js' %}></script>
    <script src={% static 'pasapp/js/form_redirect.js' %}></script>
{% endblock %}
{% block onload %} addNextRoutes() {% endblock %}
{% block content %}
    {% for project, applications in sections.items %}
        <a href="/project/{{project.id}}/" class="undecorated-link underline-hover"><h2>{{project.title}}</h2></a>
        <div>
            {{project.description}}<br>
            {% if project.capacity %}
            <b>Expected capacity: </b>{{project.capacity}}
            {% endif %}
        </div>
        {% if applications %}
            {% load html_components %}
            {% application_list_professor_interactive applications comments comment_box=True %}
        {% else %}
            <em>There are no applications for this project yet.</em>
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

pasapp/templates/pasapp/pages/professor_project_details.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} {{project.title}} {% endblock %} 
{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/app_prof_edit.js' %}></script>
    <script src={% static 'pasapp/js/form_redirect.js' %}></script> 
{% endblock %}
{% block onload %} addNextRoutes() {% endblock %}
{% block content %} 
    {% load html_components %}
    <h1>{{project.title}}</h1>
    <h3>{{project.professor.first_name}} {{project.professor.last_name}}</h3>
    {% if project.professor.id == user.id %}
        <a href="/project/{{project.id}}/edit/">Edit this project</a>
    {% endif %}
    <p>{{project.description}}</p>
    <em>Status: </em>{{project.status}}
    <br />
    <p>
        <span class="i">🛈</span> {{applications.count}} students have applied so far.<br>
        {% if project.capacity %}
            Expected capacity: {{project.capacity}}
        {% endif %} 
    </p>
    {% if projectTags %}
        <b>Tags:</b>
        {% tagbox_categorized projectTags %}
    {% endif %}
    {% if project.professor.id == user.id %}
        {% load html_components %}
        {% application_list_professor_interactive applications comments comment_box=True %}
    {% endif %}
{% endblock %}

pasapp/templates/pasapp/pages/profile.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %}{{profileUser.first_name}} {{profileUser.last_name}}{% endblock %} 
{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/tag_edit.js' %}></script>
    <script>
        {% for userTag in userTags %}
            tagSet.add({{userTag.id}});
        {% endfor %}
    </script>
{% endblock %}
{% block onload %} updateForm() {% endblock %}
{% block content %}
    {% load custom_filters %}
    {% load html_components %}
    <h2>{{profileUser.first_name}} {{profileUser.last_name}}</h2>
    {% if profileUser|is_professor %}
        <div class='professor-label'>Professor</div>
    {% else %}
        <div class='student-label'>Student</div>
    {% endif %}
    <p>Email: <a href="mailto:{{profileUser.email}}">{{profileUser.email}}</a></p>
    {% if profileUser|is_student %}
        {% tagbox_categorized userTags|academic id='tagBox-fixed' %}
        <br>
    {% endif %}
    {% if user.id == profileUser.id %}
        <form action="/user/{{profileUser.username}}/" method="post">
            {% csrf_token %}
            <input type="hidden" name="tags" id="id_tags" value="">
            {% if user|is_student %}
                {% tags_dropdown tags|academic:False %}
                <br>
                {% tagbox_categorized userTags|academic:False True %}
            {% else %}
                {% tags_dropdown tags %}
                <br>
                {% tagbox_categorized userTags True %}
            {% endif %}
            <br>
            <input type="submit" value="Save changes"/>
        </form>
    {% elif profileUser|is_student %}
        {% tagbox_categorized userTags|academic:False %}
    {% else %}
        {% tagbox_categorized userTags %}
    {% endif %}
{% endblock %}

pasapp/templates/pasapp/pages/project_applications.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} {{project.title}} Applications {% endblock %} 
{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/form_redirect.js' %}></script>
{% endblock %}
{% block onload %} addNextRoutes() {% endblock %}
{% block content %} 
  {% load html_components %}
  {% load custom_filters %}
    <h2>{{project.title}}</h2>
    <p>{{project.description}}</p>
    {% if applications %}
    <ul>
      {% for application in applications %}
      {% application_professor application comments|for_application:application buttons=True comment_box=True %}
      {% endfor %}
    </ul>
    {% else %}
    <p>No applications for this project have been sent yet.</p>
    {% endif %}
{% endblock %}

pasapp/templates/pasapp/pages/register.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} Register {% endblock %} 
{% block content %} 
    <form action="/register/" method="post">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="Sign Up" />
    </form>
{% endblock %}

pasapp/templates/pasapp/pages/student_applications.html
{% extends 'pasapp/templates/base_template.html' %} 

{% block title %} My Applications {% endblock %}
{% block imports %}
    {% load static %}
    <script src={% static 'pasapp/js/app_student_edit.js' %}></script>
    <script src={% static 'pasapp/js/form_redirect.js' %}></script>
{% endblock %}
{% block onload %} addNextRoutes() {% endblock %}
{% block content %}
    {% load html_components %}
    {% load custom_filters %}
    {% if applications or closedApplications %}
    <form action="/applications/update_priorities/" method="post">
        {% csrf_token %}
        <ol id="student-priority-list">
        {% for i in 8|times %}
            {% if i <= 5 %}
            <li class="priorityLi">
            {% else %}
            <li class="priorityLi overflow">
            {% endif %}
                <select class="prioritySelect" name="priority{{i}}" oninput="checkForConflicts(this)">
                    <option value="">--</option>
                    {% for application in applications %}
                        {% if application.priority == i %}
                            <option value={{application.id}} selected>{{application.project.title}}</option>
                        {% else %}
                            <option value={{application.id}}>{{application.project.title}}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </li>
        {% endfor %}
        </ol>
        <input type="submit" value="Update Priorities"/>
    </form>
    <form action="/applications/update_student_status/" method="post" id="status_edit_form">
        {% csrf_token %}
        <input type="hidden" name="application" id="status_id">
        <input type="hidden" name="state" id="status_state">
    </form>
        <ol id="student-applications-list">
        {% if offeredApplications %}
            <h2>Extended Offers</h2>
            {% for application in offeredApplications %}
                {% application_student application user comments|for_application:application True %}
            {% endfor %}
        {% endif %}
        {% if openApplications %}
            <h2>Pending Applications</h2>
            {% for application in openApplications %}
                {% application_student application user comments|for_application:application True %}
            {% endfor %}
        {% endif %}
        {% if closedApplications %}
            <h2>Closed Applications</h2>
            {% for application in closedApplications %}
                {% application_student application user comments|for_application:application False %}
            {% endfor %}
        {% endif %}
        </ol>
    {% else %}
    <p>You have no applications to display yet!</p>
    {% endif %} 
{% endblock %}